### PR TITLE
Patterns

### PR DESCRIPTION
**Pull request by Ann-Ageeva**
Here are added the necessary templates for our project.

### CODE REVIEW

**Comment by AMyachev** [comment]
@Ann-Ageeva thanks!

**Review by AMyachev — DISMISSED** [review]

**Comment by AMyachev** [comment]
Please add the templates inside `docs/templates/` folder

**Comment by Ann-Ageeva** [comment]
@AMyachev check it, please

**Comment by AMyachev** [comment]
good

**Review by AMyachev — APPROVED** [review]

**Pull request merged**
