### PR TITLE
add neural network

### PR DESCRIPTION
**Pull request by KhromovNikita**

### CODE REVIEW

**Review by AMyachev — CHANGES_REQUESTED** [review]
Why you closed #23 ?

**Comment by KhromovNikita** [comment]
It was easier

**Comment by AMyachev** [comment]
> It was easier

You have to do it right. By reopening it, we lose context (comments made by the review, etc.) Next time, keep working on one PR.

**Comment by AMyachev** [comment]
CI should be green

**Review by AMyachev — APPROVED** [review]

**Pull request merged**
