### PR TITLE
Neural network

### PR DESCRIPTION
**Pull request by KhromovNikita**
"CNN.ipynb" - training a neural network and preserving its model
"CNN.h5" - saved neural network model
"scaler.pickle" - stored neural network data preprocessor
"Model.ipynb" - use of a neural network model

### CODE REVIEW

**Comment by AMyachev** [comment]
@KhromovNikita  why are you using .ipynb instead of .py format?

**Comment by KhromovNikita** [comment]
I worked through Jupiter Notebook, it saves files in this format. This does not add any other features.

**Comment by AMyachev** [comment]
> I worked through Jupiter Notebook, it saves files in this format. This does not add any other features.

We cannot use code in this format in our project. It can be just an example. If so you should move your files inside `examples/keras/`

**Review by AMyachev — CHANGES_REQUESTED** [review]
See comment above

**Pull request closed without merging**
